# gen_build_info.ps1 - Extract PE TimeDateStamp from DLL and generate embedded_build_info.h
# Usage: powershell -File gen_build_info.ps1 -DllPath "MeowPAPI.dll" -OutPath "embedded_build_info.h"
param(
    [Parameter(Mandatory=$true)][string]$DllPath,
    [Parameter(Mandatory=$true)][string]$OutPath
)

$bytes = [System.IO.File]::ReadAllBytes($DllPath)

# PE format: DOS header -> e_lfanew@0x3C -> PE sig(4B) + COFF header
# COFF header: Machine(2B) + NumberOfSections(2B) + TimeDateStamp(4B)
$e_lfanew = [BitConverter]::ToInt32($bytes, 0x3C)
$timeDateStamp = [BitConverter]::ToUInt32($bytes, $e_lfanew + 8)

$content = "// AUTO-GENERATED BY gen_build_info.ps1 - DO NOT EDIT`r`n"
$content += "// Embedded MeowPAPI.dll build info (PE TimeDateStamp)`r`n"
$content += "// Consumer plugins compare this with deployed DLL version to detect stale builds`r`n"
$content += "#pragma once`r`n"
$content += "#include <cstdint>`r`n"
$content += "`r`n"
$content += "namespace meowpapi {`r`n"
$content += "`r`n"
$content += "// PE TimeDateStamp: Unix epoch seconds set by linker at build time`r`n"
$content += "constexpr uint32_t kEmbeddedBuildTimestamp = ${timeDateStamp}u;`r`n"
$content += "`r`n"
$content += "} // namespace meowpapi`r`n"

[System.IO.File]::WriteAllText($OutPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "[gen_build_info] Wrote $OutPath (timestamp=$timeDateStamp)"
